openapi: 3.0.0
info:
  title: Personaccount Aggregator API
  version: 1.0.0
paths:
  /aggregate/{personId}/{accountId}:
    get:
      tags:
        - aggregate
      summary: Получить агрегированную информацию
      operationId: aggregatePersonAndAccount
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1          # ID не может быть меньше 1
            maximum: 999999     # Пример верхнего порога
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1          # ID не может быть меньше 1
      responses:
        '200':
          description: Успешная агрегация данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AggregatedInfo'
        '400':                  # Добавили описание для ошибки валидации
          description: Некорректные входные данные
        '404':
          description: Данные не найдены
components:
  schemas:
    AggregatedInfo:
      type: object
      required:                 # Помечаем поля как обязательные в ответе
        - personName
        - accountStatus
      properties:
        personName:
          type: string
          minLength: 2          # Имя не короче 2 символов
          maxLength: 50         # Ограничение длины
          example: "Barsik"
        accountStatus:
          type: string
          pattern: '^[a-z]+$'   # Статус только строчными буквами (RegEx)
          example: "delivered"