openapi: 3.0.0
info:
  title: External Person Service
  version: 1.0.0
  description: Спецификация внешнего сервиса для получения личных данных киента.
paths:
  /person/{personId}:
    get:
      tags:
        - person
      summary: Найти клиента по ID
      operationId: getPersonById
      parameters:
        - name: personId
          in: path
          required: true
          description: ID клиента для поиска
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: Клиент не найден
components:
  schemas:
    Person:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "Иванов"
        status:
          type: string
          description: Статус клиента
          enum: [active, blocked, inactive]