openapi: 3.0.0
info:
  title: External Pet Service
  version: 1.0.0
  description: Спецификация внешнего сервиса для получения данных о питомцах.
paths:
  /pet/{petId}:
    get:
      tags:
        - pet
      summary: Найти питомца по ID
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          description: ID питомца для поиска
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Питомец не найден
components:
  schemas:
    Pet:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "Barsik"
        status:
          type: string
          description: Статус питомца в магазине
          enum: [available, pending, sold]